name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["litewallet-android/1"]
assignees:
  - joskie
  - kcw-grunt
body:
  - type: markdown
    attributes:
      value: |
        We feel bug reports are extremely valuable. Thanks for this report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: describe-what-happened
    attributes:
      label: Describe what happened.
      description: What did you expect to happen?
      placeholder: Tell us what actually happened.
      value: "Drat! A bug."
    validations:
      required: true
  - type: dropdown
    id: os-version
    attributes:
      label: OS Version
      description: What version of Android OS is running on your device?
      multiple: false
      options:
        - Android 14 | Level 34 (Default)
        - Android 13 | Level 33 
        - Android 12 | Level 32 
        - Android 11 | Level 30 
        - Android 10 | Level 29 
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: app-version
    attributes:
      label: Which version of Litewallet are you running?
      multiple: false
      options:
        - v2.10.0
        - v2.9.1
        - v2.9.0
        - v2.8.4
        - Other
