name: 🦺[Tech Debt]
description:  An issue that maintains/strengthens the Litewallet Android code or system and **not** necessarily visible in the UI
title: "🦺[Tech Debt]: "
labels: ["🦺 tech debt"]
projects: ["litecoin-foundation/3"]
assignees: 
  - josikie
  - kcw-grunt
body:
  - type: markdown
    attributes:
      value: |
        Work needed to maintain the codebase.
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: Describe the work to be done
      placeholder: e.g; Update a library or update some business logic
      value: |
        - [ ] Action 1
        - [ ] Action 2
        - [ ] Action ...
        - [ ] Action n
    validations:
      required: true
