name: 🥳[NEW USER Feature REQUEST]
description: An issue for when Litewallet Android is not operating as expected.
title: "🥳[Feature]: "
labels: ["🥳 feature"]
projects: ["litecoin-foundation/3"]
assignees: 
  - kcw-grunt
body:
  - type: markdown
    attributes:
      value: |
        Bug reports are extremely valuable. Thanks for this report! 
  - type: textarea
    id: device-model
    attributes:
      label: Device model
      description: Which is your Android device?
      placeholder: Android model
      value: "Do you have a Samsung Galaxy S23 Ultra or Google Pixel 7A or something else?"
    validations:
      required: true    # ---
# name: Feature request
# about: Suggest an idea for Litewallet
# title: ''
# labels: ''
# assignees: ''

# ---

# **Is your feature request related to a problem? Please describe.**
# A clear and concise description of what the problem is. Ex. I'm always frustrated when...

# **Describe the solution you'd like**
# A clear and concise description of what you want to happen.

# **Describe alternatives you've considered**
# A clear and concise description of any alternative solutions or features you've considered

# **Additional context**
# Add any other context or screenshots about the feature request here.
