name: 🥳[NEW SPIKE]
description: An issue for when Litewallet Android is not operating as expected.
title: "🥳[Feature]: "
labels: ["🥳 feature"]
projects: ["litecoin-foundation/3"]
assignees: 
  - kcw-grunt
body:
  - type: markdown
    attributes:
      value: |
        Bug reports are extremely valuable. Thanks for this report! 
  - type: textarea
    id: device-model
    attributes:
      label: Device model
      description: Which is your Android device?
      placeholder: Android model
      value: "Do you have a Samsung Galaxy S23 Ultra or Google Pixel 7A or something else?"
    validations:
      required: true   

# ---
# name: 📌[Spike] 
# about: An issue where no code is written but some research and planning is done for Litewallet Android
# title: '📌[Spike]'
# labels: 'spike'
# assignees: 'mosadialiou'

# ---
# ## Subject
